### ISSUE TITLE
"requests.exceptions.ConnectionError " during running full_mani_skill_example scripts

### ISSUE THREAD

**Issue by SieRaX** [haosulab/ManiSkill-Learn#14]
I was trying to run the scripts in `scripts/full_mani_skill_example`. However, I got the error message like below. 
```
ManiSkill-Track1  ✗ scripts/full_mani_skill_example/run_bc.sh
Traceback (most recent call last):
  File "/opt/conda/envs/mani_skill/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/opt/conda/envs/mani_skill/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/conda/envs/mani_skill/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/mani_skill/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/conda/envs/mani_skill/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/conda/envs/mani_skill/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/conda/envs/mani_skill/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/opt/conda/envs/mani_skill/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f73c8aad7c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/mani_skill/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/conda/envs/mani_skill/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/conda/envs/mani_skill/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage1.ucsd.edu', port=443): Max retries exceeded with url: /datasets/PartNetMobilityScrambled/1040.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c8aad7c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/mani_skill/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/mani_skill/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/ManiSkillChallenge/ManiSkill-Track1/tools/run_rl.py", line 272, in <module>
    main()
  File "/root/ManiSkillChallenge/ManiSkill-Track1/tools/run_rl.py", line 159, in main
    evaluator = build_evaluation(eval_cfg)
  File "/root/ManiSkillChallenge/ManiSkill-Track1/mani_skill_learn/env/builder.py", line 27, in build_evaluation
    return build_from_cfg(cfg, EVALUATIONS, default_args)
  File "/root/ManiSkillChallenge/ManiSkill-Track1/mani_skill_learn/utils/meta/registry.py", line 132, in build_from_cfg
    return obj_cls(**args)
  File "/root/ManiSkillChallenge/ManiSkill-Track1/mani_skill_learn/env/evaluation.py", line 36, in __init__
    self.env = build_env(env_cfg)
  File "/root/ManiSkillChallenge/ManiSkill-Track1/mani_skill_learn/env/env_utils.py", line 95, in build_env
    return build_from_cfg(cfg, ENVS, default_args)
  File "/root/ManiSkillChallenge/ManiSkill-Track1/mani_skill_learn/utils/meta/registry.py", line 132, in build_from_cfg
    return obj_cls(**args)
  File "/root/ManiSkillChallenge/ManiSkill-Track1/mani_skill_learn/env/env_utils.py", line 60, in make_gym_env
    env = gym.make(env_name, **tmp_kwargs)
  File "/opt/conda/envs/mani_skill/lib/python3.8/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/opt/conda/envs/mani_skill/lib/python3.8/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/opt/conda/envs/mani_skill/lib/python3.8/site-packages/gym/envs/registration.py", line 60, in make
    env = cls(**_kwargs)
  File "/root/ManiSkillChallenge/ManiSkill/mani_skill/env/open_cabinet_door_drawer.py", line 364, in __init__
    super().__init__(
  File "/root/ManiSkillChallenge/ManiSkill/mani_skill/env/open_cabinet_door_drawer.py", line 27, in __init__
    super().__init__(
  File "/root/ManiSkillChallenge/ManiSkill/mani_skill/env/base_env.py", line 93, in __init__
    obs = self.reset(level=0)
  File "/root/ManiSkillChallenge/ManiSkill/mani_skill/env/open_cabinet_door_drawer.py", line 39, in reset
    super().reset(*args, **kwargs)
  File "/root/ManiSkillChallenge/ManiSkill/mani_skill/env/base_env.py", line 164, in reset
    self._load_articulations()
  File "/root/ManiSkillChallenge/ManiSkill/mani_skill/env/base_env.py", line 259, in _load_articulations
    urdf = download_data(
  File "/root/ManiSkillChallenge/ManiSkill/mani_skill/env/base_env.py", line 42, in download_data
    r = requests.get(url, stream=True)
  File "/opt/conda/envs/mani_skill/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/conda/envs/mani_skill/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/conda/envs/mani_skill/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/envs/mani_skill/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/envs/mani_skill/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage1.ucsd.edu', port=443): Max retries exceeded with url: /datasets/PartNetMobilityScrambled/1040.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c8aad7c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```
It seems that the code could not connect to `storage1.ucsd.edu` host. 
Are there host any issues right now or is this my machine problem? Thank you.

**Comment by SieRaX** [comment]
Never mind! It was my docker problem! Thanks!
