### ISSUE TITLE
ImportError: cannot import name 'get_one_device' from 'mani_skill_learn.utils.torch'

### ISSUE THREAD

**Issue by arjung128** [haosulab/ManiSkill-Learn#17]
I am trying to run the evaluation script using the following command:
`
python -m tools.run_rl configs/bc/mani_skill_point_cloud_transformer.py --gpu-ids=0 --cfg-options "env_cfg.env_name=OpenCabinetDrawer_1045_link_0-v0" "eval_cfg.save_video=True" "eval_cfg.num=10" "eval_cfg.use_log=True" --work-dir=./test/OpenCabinetDrawer_1045_link_0-v0_pcd --resume-from=./example_mani_skill_data/OpenCabinetDrawer_1045_link_0-v0_PN_Transformer.ckpt --evaluation`

And I get the following output:

```
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

Size of image in the rendered video (160, 400, 3)
/bin/sh: 1: gcc: not found
OpenCabinetDrawer_1045_link_0-v0 - INFO - 2021-11-03 21:01:51 - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.8.10 (default, Jun  4 2021, 15:09:15) [GCC 7.5.0]
CUDA available: False
Num of GPUs: 0
GCC: 
PyTorch: 1.10.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.3-Product Build 20210617 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.1
OpenCV: 4.5.3
mani_skill_learn: 1.0.0
------------------------------------------------------------

OpenCabinetDrawer_1045_link_0-v0 - INFO - 2021-11-03 21:01:51 - Config:
log_level = 'INFO'
stack_frame = 1
num_heads = 4
agent = dict(
    type='BC',
    batch_size=128,
    policy_cfg=dict(
        type='ContinuousPolicy',
        policy_head_cfg=dict(type='DeterministicHead', noise_std=1e-05),
        nn_cfg=dict(
            type='PointNetWithInstanceInfoV0',
            stack_frame=1,
            num_objs='num_objs',
            pcd_pn_cfg=dict(
                type='PointNetV0',
                conv_cfg=dict(
                    type='ConvMLP',
                    norm_cfg=None,
                    mlp_spec=['agent_shape + pcd_xyz_rgb_channel', 256, 256],
                    bias='auto',
                    inactivated_output=True,
                    conv_init_cfg=dict(type='xavier_init', gain=1, bias=0)),
                mlp_cfg=dict(
                    type='LinearMLP',
                    norm_cfg=None,
                    mlp_spec=[256, 256, 256],
                    bias='auto',
                    inactivated_output=True,
                    linear_init_cfg=dict(type='xavier_init', gain=1, bias=0)),
                subtract_mean_coords=True,
                max_mean_mix_aggregation=True),
            state_mlp_cfg=dict(
                type='LinearMLP',
                norm_cfg=None,
                mlp_spec=['agent_shape', 256, 256],
                bias='auto',
                inactivated_output=True,
                linear_init_cfg=dict(type='xavier_init', gain=1, bias=0)),
            transformer_cfg=dict(
                type='TransformerEncoder',
                block_cfg=dict(
                    attention_cfg=dict(
                        type='MultiHeadSelfAttention',
                        embed_dim=256,
                        num_heads=4,
                        latent_dim=32,
                        dropout=0.1),
                    mlp_cfg=dict(
                        type='LinearMLP',
                        norm_cfg=None,
                        mlp_spec=[256, 1024, 256],
                        bias='auto',
                        inactivated_output=True,
                        linear_init_cfg=dict(
                            type='xavier_init', gain=1, bias=0)),
                    dropout=0.1),
                pooling_cfg=dict(embed_dim=256, num_heads=4, latent_dim=32),
                mlp_cfg=None,
                num_blocks=6),
            final_mlp_cfg=dict(
                type='LinearMLP',
                norm_cfg=None,
                mlp_spec=[256, 256, 'action_shape'],
                bias='auto',
                inactivated_output=True,
                linear_init_cfg=dict(type='xavier_init', gain=1, bias=0))),
        optim_cfg=dict(type='Adam', lr=0.0003, weight_decay=5e-06)))
eval_cfg = dict(
    type='Evaluation',
    num=10,
    num_procs=1,
    use_hidden_state=False,
    start_state=None,
    save_traj=True,
    save_video=True,
    use_log=True,
    env_cfg=dict(
        type='gym',
        unwrapped=False,
        stack_frame=1,
        obs_mode='pointcloud',
        reward_type='dense',
        env_name='OpenCabinetDrawer_1045_link_0-v0'))
train_mfrl_cfg = dict(
    on_policy=False,
    total_steps=50000,
    warm_steps=0,
    n_steps=0,
    n_updates=500,
    n_eval=50000,
    n_checkpoint=50000,
    init_replay_buffers=
    './example_mani_skill_data/OpenCabinetDrawer_1045_link_0-v0_pcd.h5')
env_cfg = dict(
    type='gym',
    unwrapped=False,
    stack_frame=1,
    obs_mode='pointcloud',
    reward_type='dense',
    env_name='OpenCabinetDrawer_1045_link_0-v0')
replay_cfg = dict(type='ReplayMemory', capacity=1000000)
work_dir = './test/OpenCabinetDrawer_1045_link_0-v0_pcd/BC'
resume_from = './example_mani_skill_data/OpenCabinetDrawer_1045_link_0-v0_PN_Transformer.ckpt'

OpenCabinetDrawer_1045_link_0-v0 - INFO - 2021-11-03 21:01:51 - Set random seed to None
OpenCabinetDrawer_1045_link_0-v0 - INFO - 2021-11-03 21:01:52 - State shape:{'pointcloud': {'rgb': (1200, 3), 'xyz': (1200, 3), 'seg': (1200, 3)}, 'state': 38}, action shape:Box(-1.0, 1.0, (13,), float32)
Not support gpu usage printing
Traceback (most recent call last):
  File "/home/arjung2/miniconda3/envs/mani_skill/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/arjung2/miniconda3/envs/mani_skill/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/arjung2/sapien/ManiSkill-Learn/tools/run_rl.py", line 265, in <module>
    main()
  File "/home/arjung2/sapien/ManiSkill-Learn/tools/run_rl.py", line 252, in main
    from mani_skill_learn.methods.builder import MFRL, BRL
  File "/home/arjung2/sapien/ManiSkill-Learn/mani_skill_learn/methods/__init__.py", line 1, in <module>
    from .mfrl import *
  File "/home/arjung2/sapien/ManiSkill-Learn/mani_skill_learn/methods/mfrl/__init__.py", line 1, in <module>
    from .sac import SAC
  File "/home/arjung2/sapien/ManiSkill-Learn/mani_skill_learn/methods/mfrl/sac.py", line 12, in <module>
    from mani_skill_learn.networks import build_model, hard_update, soft_update
  File "/home/arjung2/sapien/ManiSkill-Learn/mani_skill_learn/networks/__init__.py", line 2, in <module>
    from .backbones import *
  File "/home/arjung2/sapien/ManiSkill-Learn/mani_skill_learn/networks/backbones/__init__.py", line 3, in <module>
    from .vae import CVAE
  File "/home/arjung2/sapien/ManiSkill-Learn/mani_skill_learn/networks/backbones/vae.py", line 6, in <module>
    from mani_skill_learn.utils.torch import get_one_device
ImportError: cannot import name 'get_one_device' from 'mani_skill_learn.utils.torch' (/home/arjung2/sapien/ManiSkill-Learn/mani_skill_learn/utils/torch/__init__.py)
```

I am doing this on a linux machine with no GPUs. Is this the reason? If so, how can this be resolved?

Thanks!

**Comment by xuanlinli17** [comment]
All ManiSkill environments require a gpu to run. I believe that without gpu many strange errors can occur.

**Comment by arjung128** [comment]
I see, thanks!
