### ISSUE TITLE
Facing an error when evaluating on PushChair environment

### ISSUE THREAD

**Issue by swyoon** [haosulab/ManiSkill-Learn#6]
Dear organizers,

As a sanity check, I am evaluating example agents given in `full_mani_skill_data/models`.

Meanwhile, an error occurred during the evaluation of the PushChair environment. The evaluations on the other environments worked fine.

My command was:
```
python -m tools.run_rl configs/bc/mani_skill_point_cloud_transformer.py --evaluation --gpu-ids=0 \
--work-dir=./test/bc_transformer_chair/ \
--resume-from ./full_mani_skill_data/models/PushChair-v0_PN_Transformer.ckpt \
--cfg-options "env_cfg.env_name=PushChair-v0" "eval_cfg.num=300" "eval_cfg.num_procs=1" "eval_cfg.use_log=True" "eval_cfg.save_traj=False"
```

The error message was:
```
Traceback (most recent call last):
  File "/home/swyoon/anaconda3/envs/mani_skill/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/swyoon/anaconda3/envs/mani_skill/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/swyoon/Projects/ManiSkill-Track1/tools/run_rl.py", line 265, in <module>
    main()
  File "/home/swyoon/Projects/ManiSkill-Track1/tools/run_rl.py", line 254, in main
    main_mfrl_brl(cfg, args, rollout, evaluator, logger)
  File "/home/swyoon/Projects/ManiSkill-Track1/tools/run_rl.py", line 120, in main_mfrl_brl
    lens, rewards, finishes = evaluator.run(agent, work_dir=eval_dir, **cfg.eval_cfg)
  File "/home/swyoon/Projects/ManiSkill-Track1/mani_skill_learn/env/evaluation.py", line 210, in run
    episode_done = self.step(action)
  File "/home/swyoon/Projects/ManiSkill-Track1/mani_skill_learn/env/evaluation.py", line 137, in step
    next_obs, reward, done, info = self.env.step(action)
  File "/home/swyoon/anaconda3/envs/mani_skill/lib/python3.8/site-packages/gym/core.py", line 268, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/swyoon/Projects/ManiSkill/mani_skill/env/base_env.py", line 559, in step
    reward, more_info = self.compute_dense_reward(action)
  File "/home/swyoon/Projects/ManiSkill/mani_skill/env/push_chair.py", line 207, in compute_dense_reward
    target_points = np.concatenate(target_points, 0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate
```

**Comment by lz1oceani** [comment]
Hi swyoon,
Thanks for reporting the error!
I think the error may come from the incomplete PartNet Mobility file under the running folder. Could you delete that folder and rerun the scripts?

**Comment by swyoon** [comment]
Removing `partnet-mobility-dataset` directory and rerunning the evaluation script solves the problem. Thank you very much!
